name: Build,Analyze,scan
on:
  push:
    branches:
      - master
jobs:
  build-analyze-scan:
    name: Build
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Build and analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        #run: sonar-scanner -X  # Enable debug logging with the -X switch
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: NPM Install
        run: npm install # Add your specific npm install command

      - name: Install Trivy
        run: |
          # Scanning files
          trivy fs . > trivyfs.txt

      - name: Docker build and push
        run: |
          # Run commands to build and push Docker images
          docker build -t tic-tac-toe .
          docker tag tic-tac-toe debiprasan/tic-tac-toe:latest
          docker login -u ${{ secrets.USER_NAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push debiprasan/tic-tac-toe:latest
        env:
          DOCKER_CLI_ACI: 1
  deploy:
    needs: build-analyze-scan
    runs-on: label # Use your self-hosted runner label here
    steps:
      - name: Pull the Docker image
        run: docker pull debiprasan/tic-tac-toe:latest
      - name: Trivy image scan
        run: trivy image debiprasan/tic-tac-toe:latest # Add Trivy scan command here
      - name: Run the container
        run: docker run -d --name ticgame -p 3000:3000 debiprasan/tic-tac-toe:latest
      - name: Update kubeconfig
        run: aws eks --region "ap-south-1" update-kubeconfig --name "EKS"
      - name: Deploy to EKS
        run: kubectl apply -f deployment-service.yml
      - name: Send a Slack Notification
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#git'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}